// Generated by scripts/export-outline.ts (npm run export:outline). Do not edit:
// CI fails if this falls out of step with the grammar lessons.

/** AP vocabulary id -> the English words from it, as the grammar lessons list them. */
export const DERIVATIVES: Record<string, string[]> = {
  "absum": [
    "absent"
  ],
  "accido": [
    "accident"
  ],
  "accipio": [
    "accept"
  ],
  "acer": [
    "acrid"
  ],
  "ager": [
    "agrarian"
  ],
  "agricola": [
    "agriculture"
  ],
  "alius": [
    "alien",
    "alias"
  ],
  "alter": [
    "alternate"
  ],
  "altus": [
    "altitude"
  ],
  "ambulo": [
    "ambulance",
    "amble"
  ],
  "amicus": [
    "amicable"
  ],
  "amo": [
    "amorous",
    "amiable"
  ],
  "appello": [
    "appellation",
    "appeal"
  ],
  "aqua": [
    "aquarium",
    "aquatic"
  ],
  "ardeo": [
    "ardent",
    "arson"
  ],
  "ars": [
    "art",
    "artist"
  ],
  "audeo": [
    "audacious"
  ],
  "audio": [
    "audio",
    "audience"
  ],
  "auxilium": [
    "auxiliary"
  ],
  "avunculus": [
    "avuncular"
  ],
  "bellum": [
    "belligerent",
    "rebel"
  ],
  "bene": [
    "benefit"
  ],
  "bonus": [
    "bonus",
    "bonanza"
  ],
  "brevis": [
    "brevity",
    "abbreviate"
  ],
  "cano": [
    "chant"
  ],
  "capio": [
    "capture",
    "captive"
  ],
  "catena": [
    "chain",
    "concatenate"
  ],
  "celer": [
    "accelerate"
  ],
  "cinis": [
    "incinerate"
  ],
  "civis": [
    "civil",
    "civic"
  ],
  "clamo": [
    "clamor",
    "exclaim"
  ],
  "clarus": [
    "clarity"
  ],
  "cognosco": [
    "recognize",
    "cognition"
  ],
  "cras": [
    "procrastinate"
  ],
  "credo": [
    "credible",
    "credit"
  ],
  "cupio": [
    "cupidity"
  ],
  "cura": [
    "cure",
    "curator"
  ],
  "curro": [
    "current",
    "course"
  ],
  "debeo": [
    "debt",
    "debit"
  ],
  "deleo": [
    "delete"
  ],
  "dico": [
    "diction",
    "dictate"
  ],
  "dies": [
    "diary",
    "diurnal"
  ],
  "digitus": [
    "digit"
  ],
  "dignus": [
    "dignity"
  ],
  "disco": [
    "disciple"
  ],
  "do": [
    "donate",
    "data"
  ],
  "dominus": [
    "dominate",
    "domain"
  ],
  "domus": [
    "domestic",
    "domicile"
  ],
  "donum": [
    "donation"
  ],
  "dormio": [
    "dormitory",
    "dormant"
  ],
  "duco": [
    "duke",
    "conduct"
  ],
  "duo": [
    "duet",
    "dual"
  ],
  "dux": [
    "duke"
  ],
  "ego": [
    "ego",
    "egotist"
  ],
  "egredior": [
    "egress"
  ],
  "eo": [
    "exit",
    "transit"
  ],
  "epistula": [
    "epistle"
  ],
  "equus": [
    "equine",
    "equestrian"
  ],
  "ex": [
    "exit"
  ],
  "exitus": [
    "exit"
  ],
  "facilis": [
    "facile",
    "facility"
  ],
  "facio": [
    "fact",
    "factory"
  ],
  "fatum": [
    "fatal"
  ],
  "felix": [
    "felicity"
  ],
  "femina": [
    "feminine"
  ],
  "fero": [
    "transfer",
    "fertile"
  ],
  "filia": [
    "filial"
  ],
  "filius": [
    "filial"
  ],
  "finis": [
    "finish",
    "confine"
  ],
  "fortis": [
    "fortitude",
    "fortify"
  ],
  "fugio": [
    "fugitive",
    "refuge"
  ],
  "gladius": [
    "gladiator",
    "gladiolus"
  ],
  "habeo": [
    "habit"
  ],
  "habito": [
    "inhabit",
    "habitat"
  ],
  "homo": [
    "homicide",
    "human"
  ],
  "hora": [
    "hour",
    "horoscope"
  ],
  "hostis": [
    "hostile"
  ],
  "idem": [
    "identity"
  ],
  "ignis": [
    "ignite"
  ],
  "imago": [
    "image",
    "imagination"
  ],
  "impetus": [
    "impetus"
  ],
  "incendium": [
    "incendiary"
  ],
  "incipio": [
    "incipient",
    "inception"
  ],
  "insula": [
    "peninsula",
    "insulate"
  ],
  "intellego": [
    "intelligent"
  ],
  "invenio": [
    "invent"
  ],
  "iter": [
    "itinerary"
  ],
  "laboro": [
    "laboratory"
  ],
  "lacrima": [
    "lachrymose"
  ],
  "lapis": [
    "lapidary"
  ],
  "laudo": [
    "laud",
    "laudable"
  ],
  "legatus": [
    "legate",
    "delegate"
  ],
  "lego": [
    "legible",
    "lecture"
  ],
  "lex": [
    "legal"
  ],
  "libero": [
    "liberate"
  ],
  "lingua": [
    "linguist"
  ],
  "litus": [
    "littoral"
  ],
  "longus": [
    "longitude"
  ],
  "loquor": [
    "eloquent",
    "loquacious"
  ],
  "lumen": [
    "luminous"
  ],
  "magnus": [
    "magnitude",
    "magnify"
  ],
  "malus": [
    "malice",
    "malevolent"
  ],
  "manus": [
    "manual",
    "manuscript"
  ],
  "mare": [
    "marine",
    "maritime"
  ],
  "mater": [
    "maternal"
  ],
  "mens": [
    "mental"
  ],
  "miles": [
    "military",
    "militia"
  ],
  "mille": [
    "millennium",
    "mile"
  ],
  "mitto": [
    "mission",
    "transmit"
  ],
  "moneo": [
    "monitor",
    "admonish"
  ],
  "mons": [
    "mount",
    "mountain"
  ],
  "morior": [
    "mortal",
    "mortuary"
  ],
  "moror": [
    "moratorium"
  ],
  "multus": [
    "multitude",
    "multiply"
  ],
  "narro": [
    "narrate"
  ],
  "nascor": [
    "native",
    "nation"
  ],
  "nauta": [
    "nautical"
  ],
  "navigo": [
    "navigate"
  ],
  "navis": [
    "naval",
    "navy"
  ],
  "nego": [
    "negative",
    "renege"
  ],
  "nomen": [
    "nominate",
    "noun"
  ],
  "nox": [
    "nocturnal"
  ],
  "nullus": [
    "null"
  ],
  "nuntio": [
    "announce"
  ],
  "omnis": [
    "omnibus",
    "omnipotent"
  ],
  "opus": [
    "opus",
    "operate"
  ],
  "oro": [
    "oration",
    "oracle"
  ],
  "paro": [
    "prepare"
  ],
  "pater": [
    "paternal",
    "patriot"
  ],
  "patior": [
    "patient",
    "passion"
  ],
  "pax": [
    "pacify",
    "pacific"
  ],
  "periculumorpericlum": [
    "peril"
  ],
  "persuadeo": [
    "persuasion"
  ],
  "peto": [
    "petition",
    "compete"
  ],
  "poeta": [
    "poet",
    "poetry"
  ],
  "pono": [
    "position",
    "deposit"
  ],
  "pons": [
    "pontoon"
  ],
  "porto": [
    "portable",
    "transport"
  ],
  "possum": [
    "possible",
    "potent"
  ],
  "primus": [
    "primary",
    "prime"
  ],
  "prope": [
    "propinquity"
  ],
  "puer": [
    "puerile"
  ],
  "pugno": [
    "pugnacious"
  ],
  "pulcher": [
    "pulchritude"
  ],
  "puto": [
    "compute",
    "reputation"
  ],
  "quaero": [
    "query",
    "question"
  ],
  "refero": [
    "refer",
    "relate"
  ],
  "rego": [
    "regent",
    "regulate"
  ],
  "relinquo": [
    "relinquish",
    "relic"
  ],
  "res": [
    "real",
    "republic"
  ],
  "rex": [
    "regal",
    "reign"
  ],
  "rideo": [
    "ridiculous",
    "deride"
  ],
  "rogo": [
    "interrogate"
  ],
  "saluto": [
    "salute"
  ],
  "scio": [
    "science"
  ],
  "scribo": [
    "scribe",
    "script"
  ],
  "sentio": [
    "sense",
    "sentiment"
  ],
  "sequor": [
    "sequel",
    "consequence"
  ],
  "servo": [
    "preserve",
    "conserve"
  ],
  "servus": [
    "servile",
    "servant"
  ],
  "signum": [
    "signal",
    "signature"
  ],
  "silva": [
    "sylvan"
  ],
  "similis": [
    "similar"
  ],
  "sine": [
    "sinecure"
  ],
  "sonus": [
    "sonic"
  ],
  "specto": [
    "spectator",
    "inspect"
  ],
  "spero": [
    "desperate"
  ],
  "sto": [
    "station",
    "status"
  ],
  "sub": [
    "submarine"
  ],
  "tardus": [
    "tardy"
  ],
  "tempus": [
    "temporary",
    "tempo"
  ],
  "teneo": [
    "tenacious",
    "tenant"
  ],
  "terra": [
    "terrain",
    "territory"
  ],
  "timeo": [
    "timid"
  ],
  "totus": [
    "total"
  ],
  "trado": [
    "tradition",
    "traitor"
  ],
  "umbra": [
    "umbrella"
  ],
  "unus": [
    "unit",
    "unanimous"
  ],
  "urbs": [
    "urban"
  ],
  "utor": [
    "use",
    "utensil"
  ],
  "venio": [
    "convene",
    "venue"
  ],
  "ventus": [
    "vent"
  ],
  "verus": [
    "verify",
    "verdict"
  ],
  "via": [
    "via",
    "viaduct"
  ],
  "video": [
    "video",
    "vision"
  ],
  "vinco": [
    "victory",
    "invincible"
  ],
  "vir": [
    "virile",
    "virtue"
  ],
  "vivo": [
    "vivid",
    "revive"
  ],
  "voco": [
    "vocal",
    "invoke"
  ],
  "volo": [
    "volition",
    "voluntary"
  ]
};
