import Foundation

/// The Aeneid scansion corpus — every line whose scansion the metre forces,
/// generated by scripts/build-scansion.mjs into public/scansion (one file per
/// book), and bundled with the app from the same files. A port of
/// src/data/scansionCorpus.ts.
public struct ScansionCorpus: Sendable {
    public struct BookInfo: Codable, Sendable, Hashable {
        public let book: Int
        public let count: Int
        public let sourceCount: Int
    }

    public struct Index: Codable, Sendable {
        public let work: String
        public let author: String
        public let source: String
        public let books: [BookInfo]
        public let total: Int
        /// Verse lines in the whole source text, before ambiguous ones are dropped.
        public let sourceTotal: Int
    }

    public struct PackedLine: Codable, Sendable {
        let i: Int
        let t: String
        let s: String
        let f: String
        let e: [Int]
        let c: String
    }

    struct PackedBook: Codable {
        let b: Int
        let n: Int
        let l: [PackedLine]
    }

    public let directory: URL
    public let index: Index

    public init(directory: URL) throws {
        self.directory = directory
        index = try JSONDecoder().decode(Index.self, from: Data(contentsOf: directory.appendingPathComponent("index.json")))
    }

    public func loadBook(_ book: Int) throws -> [ScansionLine] {
        let data = try Data(contentsOf: directory.appendingPathComponent("aen\(book).json"))
        let packed = try JSONDecoder().decode(PackedBook.self, from: data)
        return packed.l.map { Self.unpack(book: book, $0) }
    }

    /// A line id's book and line number — the web's `parseLineId`.
    public static func parseLineId(_ id: String) -> (book: Int, line: Int)? {
        let parts = id.split(separator: "-")
        guard parts.count == 4, parts[0] == "scan", parts[1] == "aen", let b = Int(parts[2]), let l = Int(parts[3]) else { return nil }
        return (b, l)
    }

    /// A book chosen at random, weighted by its line count, so every line in
    /// the corpus is equally likely rather than every book.
    public func randomBook() -> Int {
        let total = index.books.reduce(0) { $0 + $1.count }
        guard total > 0 else { return 1 }
        var r = Double.random(in: 0..<Double(total))
        for b in index.books {
            r -= Double(b.count)
            if r <= 0 { return b.book }
        }
        return index.books.last?.book ?? 1
    }

    static let caesuraTypes: [Character: String] = [
        "p": "penthemimeral", "h": "hephthemimeral", "t": "trithemimeral", "b": "bucolic",
    ]

    /// Rebuilds a full line from its packed form. Quantities aren't stored: a
    /// dactyl is long-short-short and a spondee long-long, so walking the feet
    /// over the non-elided syllables reproduces every one. The last syllable
    /// is anceps — marked long, flagged, and accepted either way.
    static func unpack(book: Int, _ p: PackedLine) -> ScansionLine {
        let elided = Set(p.e)
        var texts: [String] = []
        var wordIndex: [Int] = []
        var wi = 0
        var current = ""
        for ch in p.s {
            if ch == "|" || ch == " " {
                texts.append(current)
                wordIndex.append(wi)
                current = ""
                if ch == " " { wi += 1 }
                continue
            }
            current.append(ch)
        }
        if !current.isEmpty {
            texts.append(current)
            wordIndex.append(wi)
        }
        let startsWord = wordIndex.indices.map { $0 == 0 || wordIndex[$0] != wordIndex[$0 - 1] }
        let feet = p.f.map { $0 == "D" ? "dactyl" : "spondee" }
        var pattern: [String] = []
        for f in feet {
            pattern.append("long")
            if f == "dactyl" { pattern += ["short", "short"] } else { pattern.append("long") }
        }
        let metricalCount = texts.count - elided.count
        var syllables: [ScannedSyllable] = []
        var mi = 0
        for i in texts.indices {
            if elided.contains(i) {
                syllables.append(ScannedSyllable(text: texts[i], quantity: "short", elides: true, startsWord: startsWord[i]))
                continue
            }
            let isLast = mi == metricalCount - 1
            syllables.append(ScannedSyllable(text: texts[i], quantity: mi < pattern.count ? pattern[mi] : "long",
                                             elides: false, startsWord: startsWord[i], anceps: isLast ? true : nil))
            mi += 1
        }
        let caesurae: [Caesura] = p.c.isEmpty ? [] : p.c.split(separator: ",").map { tok in
            Caesura(afterSyllable: Int(tok.dropLast()) ?? 0, type: caesuraTypes[tok.last ?? "p"] ?? "penthemimeral")
        }
        return ScansionLine(id: "scan-aen-\(book)-\(p.i)", passageId: "aen-\(book)", citation: "Aeneid \(book).\(p.i)",
                            latin: p.t, feet: feet, syllables: syllables, caesurae: caesurae, notes: "")
    }
}
