package com.norvodesigns.lectio.core

import kotlinx.serialization.Serializable
import kotlin.math.max
import kotlin.random.Random

/**
 * The Aeneid scansion corpus: every line whose scansion the metre forces,
 * generated by scripts/build-scansion.mjs into public/scansion (one file per
 * book), and bundled with the app from the same files. A port of
 * src/data/scansionCorpus.ts.
 */
class ScansionCorpus(private val source: ContentSource) {
    @Serializable
    data class BookInfo(val book: Int, val count: Int, val sourceCount: Int)

    @Serializable
    data class Index(
        val work: String,
        val author: String,
        val source: String,
        val books: List<BookInfo>,
        val total: Int,
        /** Verse lines in the whole source text, before ambiguous ones are dropped. */
        val sourceTotal: Int,
    )

    @Serializable
    data class PackedLine(val i: Int, val t: String, val s: String, val f: String, val e: List<Int>, val c: String)

    @Serializable
    internal data class PackedBook(val b: Int, val n: Int, val l: List<PackedLine>)

    val index: Index = LectioJson.decodeFromString(Index.serializer(), source.readText("index.json"))

    fun loadBook(book: Int): List<ScansionLine> {
        val packed = LectioJson.decodeFromString(PackedBook.serializer(), source.readText("aen$book.json"))
        return packed.l.map { unpack(book, it) }
    }

    /** A book chosen at random, weighted by its line count, so every line in the corpus is equally likely rather than every book. */
    fun randomBook(rng: Random = Random.Default): Int {
        val total = index.books.sumOf { it.count }
        if (total <= 0) return 1
        var r = rng.nextDouble(0.0, total.toDouble())
        for (b in index.books) {
            r -= b.count
            if (r <= 0) return b.book
        }
        return index.books.lastOrNull()?.book ?: 1
    }

    companion object {
        /** A line id's book and line number: the web's `parseLineId`. */
        fun parseLineId(id: String): Pair<Int, Int>? {
            val parts = id.split("-")
            if (parts.size != 4 || parts[0] != "scan" || parts[1] != "aen") return null
            val b = parts[2].toIntOrNull() ?: return null
            val l = parts[3].toIntOrNull() ?: return null
            return b to l
        }

        private val caesuraTypes = mapOf('p' to "penthemimeral", 'h' to "hephthemimeral", 't' to "trithemimeral", 'b' to "bucolic")

        /**
         * Rebuilds a full line from its packed form. Quantities aren't stored:
         * a dactyl is long-short-short and a spondee long-long, so walking the
         * feet over the non-elided syllables reproduces every one. The last
         * syllable is anceps: marked long, flagged, and accepted either way.
         */
        fun unpack(book: Int, p: PackedLine): ScansionLine {
            val elided = p.e.toSet()
            val texts = ArrayList<String>()
            val wordIndex = ArrayList<Int>()
            var wi = 0
            val current = StringBuilder()
            for (ch in p.s) {
                if (ch == '|' || ch == ' ') {
                    texts.add(current.toString())
                    wordIndex.add(wi)
                    current.setLength(0)
                    if (ch == ' ') wi++
                    continue
                }
                current.append(ch)
            }
            if (current.isNotEmpty()) {
                texts.add(current.toString())
                wordIndex.add(wi)
            }
            val startsWord = wordIndex.indices.map { it == 0 || wordIndex[it] != wordIndex[it - 1] }
            val feet = p.f.map { if (it == 'D') "dactyl" else "spondee" }
            val pattern = ArrayList<String>()
            for (f in feet) {
                pattern.add("long")
                if (f == "dactyl") { pattern.add("short"); pattern.add("short") } else pattern.add("long")
            }
            val metricalCount = texts.size - elided.size
            val syllables = ArrayList<ScannedSyllable>()
            var mi = 0
            for (i in texts.indices) {
                if (i in elided) {
                    syllables.add(ScannedSyllable(texts[i], "short", elides = true, startsWord = startsWord[i]))
                    continue
                }
                val isLast = mi == metricalCount - 1
                syllables.add(
                    ScannedSyllable(
                        texts[i], if (mi < pattern.size) pattern[mi] else "long",
                        elides = false, startsWord = startsWord[i], anceps = if (isLast) true else null,
                    ),
                )
                mi++
            }
            val caesurae = if (p.c.isEmpty()) emptyList() else p.c.split(",").map { tok ->
                Caesura(tok.dropLast(1).toIntOrNull() ?: 0, caesuraTypes[tok.lastOrNull() ?: 'p'] ?: "penthemimeral")
            }
            return ScansionLine(
                id = "scan-aen-$book-${p.i}", passageId = "aen-$book", citation = "Aeneid $book.${p.i}",
                latin = p.t, feet = feet, syllables = syllables, caesurae = caesurae, notes = "",
            )
        }
    }
}

/**
 * What a student has done to one line so far, and how it scores: the rules of
 * src/app/scansion/ScansionLab.tsx, kept out of the UI so they can be tested.
 *
 * Three things count, not one: every syllable's quantity, the five foot
 * divisions, and every elision judgment. All quantities right but the feet
 * wrongly divided, or an elision missed, is not a scanned line.
 */
class ScansionWork(val line: ScansionLine, draft: ScansionDraft?) {
    /** One per syllable: "long", "short" or null. */
    var marks: MutableList<String?>
        private set

    /** Raw syllable indices after which the student ruled a boundary. */
    var divisions: MutableList<Int>
        private set

    /** Syllable indices the student claims elide into the next word. */
    var elisions: MutableSet<Int>
        private set
    var checked: Boolean
        private set

    init {
        if (draft != null && draft.marks.size == line.syllables.size) {
            marks = draft.marks.toMutableList()
            divisions = draft.divisions.toMutableList()
            elisions = (draft.elisions ?: emptyList()).toMutableSet()
            checked = draft.checked ?: false
        } else {
            marks = MutableList(line.syllables.size) { null }
            divisions = mutableListOf()
            elisions = mutableSetOf()
            checked = false
        }
    }

    val draft: ScansionDraft
        get() = ScansionDraft(marks.toList(), divisions.toList(), if (checked) true else null, elisions.sorted())

    val isBlank: Boolean get() = marks.all { it == null } && divisions.isEmpty() && elisions.isEmpty()

    fun markChecked() {
        checked = true
    }

    /* Views of the line */

    /**
     * Whether syllable [i] currently counts as elided: the real answer once
     * checked, but before that only what the student has claimed. A syllable
     * that truly elides but hasn't been claimed must look and behave exactly
     * like any other, or the foot maths would give the answer away.
     */
    fun elidesAt(i: Int): Boolean = if (checked) line.syllables[i].isElided else i in elisions

    /** Syllables that count metrically, per the real answer. */
    val metricalIndices: List<Int> get() = line.syllables.indices.filter { !line.syllables[it].isElided }

    /** Syllables that count metrically from the student's own current view. */
    val studentMetricalIndices: List<Int> get() = line.syllables.indices.filter { !elidesAt(it) }

    /** Word-final syllables with a word after them: every junction where elision is a live question. */
    val elidableIndices: List<Int>
        get() = line.syllables.indices.filter { it < line.syllables.size - 1 && isWordFinal(line.syllables, it) }

    /** The divisions the metre requires, in metrical-index terms. */
    val correctDivisions: List<Int>
        get() {
            val out = ArrayList<Int>()
            var acc = -1
            for (f in line.feet.dropLast(1)) {
                acc += if (f == "dactyl") 3 else 2
                out.add(acc)
            }
            return out
        }

    data class Group(
        val syllables: List<Int>,
        /** The last syllable in it that counts. */
        val endsAt: Int,
        /** Whether the student ruled a boundary after it. */
        val closed: Boolean,
    )

    /** The line split at the student's own boundaries. An elided syllable is carried with the foot it sits inside and never fills it. */
    val groups: List<Group>
        get() {
            val cuts = divisions.toSet()
            val out = ArrayList<Group>()
            var current = ArrayList<Int>()
            var lastCounted = -1
            var i = 0
            while (i < line.syllables.size) {
                current.add(i)
                if (!elidesAt(i)) {
                    lastCounted = i
                    if (i in cuts) {
                        while (i + 1 < line.syllables.size && elidesAt(i + 1)) {
                            i++
                            current.add(i)
                        }
                        out.add(Group(current, lastCounted, true))
                        current = ArrayList()
                    }
                }
                i++
            }
            if (current.isNotEmpty()) out.add(Group(current, lastCounted, false))
            return out
        }

    /** "Dactyl" or "Spondee" when the student's own marks make the group one. */
    fun footName(group: Group): String? {
        val metrical = group.syllables.filter { !elidesAt(it) }
        val shape = metrical.map { marks[it] }
        if (shape.any { it == null }) return null
        if (shape == listOf("long", "short", "short")) return "Dactyl"
        if (shape == listOf("long", "long")) return "Spondee"
        return null
    }

    /** Everything the student sees still needs a mark, and all five boundaries are in. */
    val isReady: Boolean get() = studentMetricalIndices.all { marks[it] != null } && divisions.size == 5

    /* Editing */

    /** Blank -> long -> short -> blank. */
    fun cycleMark(i: Int) {
        if (checked || elidesAt(i)) return
        marks[i] = when (marks[i]) { null -> "long"; "long" -> "short"; else -> null }
    }

    fun setMark(i: Int, mark: String?) {
        if (checked) return
        marks[i] = mark
    }

    /** A boundary can go after any syllable the student's view counts, except the last. */
    fun canDivide(after: Int): Boolean {
        if (checked || elidesAt(after)) return false
        val idx = studentMetricalIndices
        val k = idx.indexOf(after)
        return k >= 0 && k < idx.size - 1
    }

    fun toggleDivision(after: Int) {
        if (!canDivide(after)) return
        if (!divisions.remove(after)) {
            divisions.add(after)
            divisions.sort()
        }
    }

    /** Claiming an elision clears that syllable's mark and any boundary anchored to it; un-claiming leaves marks alone. */
    fun toggleElision(i: Int) {
        if (checked || i !in elidableIndices) return
        if (i in elisions) {
            elisions.remove(i)
        } else {
            elisions.add(i)
            marks[i] = null
            divisions.removeAll { it == i }
        }
    }

    /* Scoring */

    /** The final syllable is anceps: either mark is right there. */
    fun isCorrect(i: Int): Boolean {
        val mark = marks[i] ?: return false
        if (line.syllables[i].isAnceps) return true
        return mark == line.syllables[i].quantity
    }

    fun elisionCorrect(i: Int): Boolean = (i in elisions) == line.syllables[i].isElided

    /** Whether the student's boundary after raw syllable [i] is one the metre has. */
    fun boundaryCorrect(after: Int): Boolean {
        val k = metricalIndices.indexOf(after)
        return k >= 0 && k in correctDivisions
    }

    enum class SyllableResult { Ok, Wrong, Blank, WrongElision }

    fun result(i: Int): SyllableResult {
        if (line.syllables[i].isElided) return if (marks[i] == null) SyllableResult.Ok else SyllableResult.WrongElision
        if (isCorrect(i)) return SyllableResult.Ok
        return if (marks[i] == null) SyllableResult.Blank else SyllableResult.Wrong
    }

    data class Score(
        val syllables: Int, val syllablesTotal: Int,
        val boundaries: Int, val boundariesTotal: Int,
        val elisions: Int, val elisionsTotal: Int,
    ) {
        val correct: Int get() = syllables + boundaries + elisions
        val total: Int get() = syllablesTotal + boundariesTotal + elisionsTotal
    }

    val score: Score
        get() {
            val metrical = metricalIndices
            val asMetrical = divisions.map { metrical.indexOf(it) }
            val correctDivs = correctDivisions
            val elidable = elidableIndices
            return Score(
                metrical.count { isCorrect(it) }, metrical.size,
                asMetrical.count { it in correctDivs }, correctDivs.size,
                elidable.count { elisionCorrect(it) }, elidable.size,
            )
        }

    /** The principal break: penthemimeral where there is one, else the first. */
    val mainCaesura: Caesura? get() = line.caesurae.firstOrNull { it.type == "penthemimeral" } ?: line.caesurae.firstOrNull()

    companion object {
        internal fun isWordFinal(s: List<ScannedSyllable>, i: Int): Boolean = i + 1 >= s.size || s[i + 1].startsWord != false
    }
}

/** Per-line progress and badges: ports of `scansionStatsByLine`, `masteredLineIds` and `scansionBadges`. */
object ScansionStats {
    data class Line(val lineId: String, val attempts: Int, val bestAccuracy: Double, val lastAccuracy: Double, val mastered: Boolean)

    fun byLine(attempts: List<ScansionAttempt>): Map<String, Line> {
        val map = LinkedHashMap<String, Line>()
        for (a in attempts) {
            val acc = if (a.total > 0) a.correct.toDouble() / a.total else 0.0
            val cur = map[a.lineId]
            map[a.lineId] = if (cur != null) {
                cur.copy(attempts = cur.attempts + 1, bestAccuracy = max(cur.bestAccuracy, acc), lastAccuracy = acc, mastered = cur.mastered || acc == 1.0)
            } else {
                Line(a.lineId, 1, acc, acc, acc == 1.0)
            }
        }
        return map
    }

    fun mastered(attempts: List<ScansionAttempt>): Set<String> = byLine(attempts).values.filter { it.mastered }.map { it.lineId }.toSet()

    /** The unmastered line the student is weakest on, if any. */
    fun weakest(attempts: List<ScansionAttempt>): String? =
        byLine(attempts).values.filter { !it.mastered }.minByOrNull { it.bestAccuracy }?.lineId

    data class Badge(val id: String, val label: String, val detail: String, val earned: Boolean)

    fun badges(attempts: List<ScansionAttempt>, poolSize: Int): List<Badge> {
        val masteredCount = byLine(attempts).values.count { it.mastered }
        var streak = 0
        var best = 0
        for (a in attempts) {
            if (a.total > 0 && a.correct == a.total) { streak++; best = max(best, streak) } else streak = 0
        }
        val half = Math.ceil(poolSize / 2.0).toInt()
        return listOf(
            Badge("first-line", "First scan", "Scan a line for the first time.", attempts.isNotEmpty()),
            Badge("streak-5", "Five in a row", "Score a perfect line five attempts in a row.", best >= 5),
            Badge("half-mastered", "Halfway there", "Master half of the loaded lines ($half of $poolSize).", poolSize > 0 && masteredCount >= half),
            Badge("all-mastered", "Full mastery", "Score a perfect scansion on every one of the $poolSize loaded lines.", poolSize > 0 && masteredCount >= poolSize),
            Badge("veteran", "Fifty scans", "Complete fifty scansion attempts in total.", attempts.size >= 50),
        )
    }
}
