/**
 * Writes src/data/curriculum/outline.generated.ts: the course without its
 * steps, plus two counts the dashboard shows, so the pages that only list
 * lessons don't download every exercise, passage and gloss. Run after
 * changing the course; CI fails if it is stale.
 *
 *   npm run export:outline
 *   npm run export:outline -- --check   (verifies, writes nothing)
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { COURSE } from '../src/data/curriculum';
import { requiredPassages } from '../src/data/passages';
import { coreVocabulary } from '../src/data/vocabulary';
import { supplementaryVocabulary } from '../src/data/supplementaryVocabulary';
import { outlineOf } from '../src/data/curriculum/outlineOf';

const out = `// Generated by scripts/export-outline.ts (npm run export:outline). Do not edit:
// CI fails if this falls out of step with the course.
import type { OutlineLevel } from './types';

export const OUTLINE: OutlineLevel[] = ${JSON.stringify(outlineOf(COURSE), null, 2)};

/** Ids of the passages on the AP syllabus. */
export const REQUIRED_PASSAGE_IDS: string[] = ${JSON.stringify(requiredPassages.map((p) => p.id))};

/** Words in the core and supplementary vocabulary together. */
export const VOCAB_COUNT = ${coreVocabulary.length + supplementaryVocabulary.length};
`;
const path = 'src/data/curriculum/outline.generated.ts';
if (process.argv.includes('--check')) {
  if (!existsSync(path) || readFileSync(path, 'utf8') !== out) {
    console.error('The course outline is stale. Run `npm run export:outline`.');
    process.exit(1);
  }
  console.log('The course outline is up to date.');
} else {
  writeFileSync(path, out);
  console.log(`Wrote the outline: ${COURSE.length} levels, ${COURSE.flatMap((l) => l.units).length} units.`);
}
