/**
 * Writes src/data/curriculum/outline.generated.ts: the course without its
 * steps, plus two counts the dashboard shows, so the pages that only list
 * lessons don't download every exercise, passage and gloss. Run after
 * changing the course; CI fails if it is stale.
 *
 *   npm run export:outline
 *   npm run export:outline -- --check   (verifies, writes nothing)
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { COURSE, GRAMMAR_LEVELS } from '../src/data/curriculum';
import { requiredPassages } from '../src/data/passages';
import { coreVocabulary } from '../src/data/vocabulary';
import { supplementaryVocabulary } from '../src/data/supplementaryVocabulary';
import { outlineOf } from '../src/data/curriculum/outlineOf';

const out = `// Generated by scripts/export-outline.ts (npm run export:outline). Do not edit:
// CI fails if this falls out of step with the course.
import type { OutlineLevel } from './types';

export const OUTLINE: OutlineLevel[] = ${JSON.stringify(outlineOf(COURSE), null, 2)};

/** Ids of the passages on the AP syllabus. */
export const REQUIRED_PASSAGE_IDS: string[] = ${JSON.stringify(requiredPassages.map((p) => p.id))};

/** Words in the core and supplementary vocabulary together. */
export const VOCAB_COUNT = ${coreVocabulary.length + supplementaryVocabulary.length};
`;
// The English derivatives the grammar lessons list for AP-list words, first
// mention only, for the vocabulary track (verba/build.ts) to show beside them.
const derivatives: Record<string, string[]> = {};
for (const level of GRAMMAR_LEVELS) {
  for (const unit of level.units) {
    for (const lesson of unit.lessons) {
      for (const w of lesson.words) {
        if (w.vocabId && w.derivatives?.length && !derivatives[w.vocabId]) derivatives[w.vocabId] = w.derivatives;
      }
    }
  }
}
const sorted = Object.fromEntries(Object.keys(derivatives).sort().map((k) => [k, derivatives[k]]));
const derivativesOut = `// Generated by scripts/export-outline.ts (npm run export:outline). Do not edit:
// CI fails if this falls out of step with the grammar lessons.

/** AP vocabulary id -> the English words from it, as the grammar lessons list them. */
export const DERIVATIVES: Record<string, string[]> = ${JSON.stringify(sorted, null, 2)};
`;

const files: Array<[string, string]> = [
  ['src/data/curriculum/outline.generated.ts', out],
  ['src/data/curriculum/verba/derivatives.generated.ts', derivativesOut],
];
if (process.argv.includes('--check')) {
  for (const [path, body] of files) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== body) {
      console.error(`${path} is stale. Run \`npm run export:outline\`.`);
      process.exit(1);
    }
  }
  console.log('The course outline is up to date.');
} else {
  for (const [path, body] of files) writeFileSync(path, body);
  console.log(`Wrote the outline: ${COURSE.length} levels, ${COURSE.flatMap((l) => l.units).length} units; derivatives for ${Object.keys(sorted).length} AP words.`);
}
