/**
 * The scansion corpus: every line of the Aeneid whose scansion is forced by
 * the metre.
 *
 * Generated by scripts/build-scansion.mjs from the public-domain text and
 * written to public/scansion as one file per book. Roughly 6,500 of the poem's
 * 9,883 lines resolve to exactly one legal foot division; the rest are dropped
 * rather than guessed at.
 *
 * Books load on demand — the whole corpus is about a megabyte, which has no
 * business in the initial bundle when a student works through one line at a
 * time.
 */

import type { ScansionLine, ScannedSyllable, FootType } from './types';

export const AENEID_BOOKS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;
export type AeneidBook = (typeof AENEID_BOOKS)[number];

/** A line as stored on disk. See the generator for the encoding. */
interface PackedLine {
  i: number;
  t: string;
  s: string;
  f: string;
  e: number[];
  c: string;
}

interface PackedBook {
  b: number;
  n: number;
  l: PackedLine[];
}

export interface CorpusIndex {
  work: string;
  author: string;
  source: string;
  generated: string;
  books: Array<{ book: number; count: number }>;
  total: number;
}

const CAESURA_TYPES = {
  p: 'penthemimeral',
  h: 'hephthemimeral',
  t: 'trithemimeral',
  b: 'bucolic',
} as const;

/**
 * Rebuild a full line from its packed form.
 *
 * Quantities are not stored: a dactyl is long-short-short and a spondee is
 * long-long, so walking the feet over the non-elided syllables reproduces
 * every quantity exactly. The final syllable is anceps — it closes the line
 * and counts long however it actually scans — so it is marked long but
 * flagged, and the grader accepts either answer for it.
 */
export function unpackLine(book: number, p: PackedLine): ScansionLine {
  const elided = new Set(p.e);
  const texts: string[] = [];
  const wordIndex: number[] = [];
  let wi = 0;
  let current = '';

  for (const ch of p.s) {
    if (ch === '|' || ch === ' ') {
      texts.push(current);
      wordIndex.push(wi);
      current = '';
      if (ch === ' ') wi += 1;
      continue;
    }
    current += ch;
  }
  if (current) {
    texts.push(current);
    wordIndex.push(wi);
  }

  // `wordIndex` already distinguishes a syllable break (`|`) from a real word
  // break (` `) — the packer encodes that on purpose. Reduce it to "is this
  // syllable the first one of its word" once here, so the UI can show
  // syllables run together within a word without re-deriving word
  // boundaries from punctuation itself.
  const startsWord = wordIndex.map((w, i) => i === 0 || w !== wordIndex[i - 1]);

  const feet = [...p.f].map<FootType>((c) => (c === 'D' ? 'dactyl' : 'spondee'));

  // Quantities, in metrical order.
  const pattern: Array<'long' | 'short'> = [];
  for (const f of feet) {
    pattern.push('long');
    if (f === 'dactyl') pattern.push('short', 'short');
    else pattern.push('long');
  }

  const metricalCount = texts.length - elided.size;
  const syllables: ScannedSyllable[] = [];
  let mi = 0;
  for (let i = 0; i < texts.length; i += 1) {
    if (elided.has(i)) {
      syllables.push({ text: texts[i], quantity: 'short', elides: true, startsWord: startsWord[i] });
      continue;
    }
    const isLast = mi === metricalCount - 1;
    syllables.push({
      text: texts[i],
      quantity: pattern[mi] ?? 'long',
      elides: false,
      startsWord: startsWord[i],
      ...(isLast ? { anceps: true } : {}),
    });
    mi += 1;
  }

  const caesurae = p.c
    ? p.c.split(',').map((tok) => {
        const type = CAESURA_TYPES[tok.slice(-1) as keyof typeof CAESURA_TYPES];
        return { afterSyllable: Number(tok.slice(0, -1)), type };
      })
    : [];

  return {
    id: `scan-aen-${book}-${p.i}`,
    passageId: `aen-${book}`,
    citation: `Aeneid ${book}.${p.i}`,
    latin: p.t,
    feet,
    syllables,
    caesurae,
    notes: '',
  };
}

/* ------------------------------------------------------------------ */
/* Loading                                                             */
/* ------------------------------------------------------------------ */

const bookCache = new Map<number, ScansionLine[]>();
const inFlight = new Map<number, Promise<ScansionLine[]>>();
let indexCache: CorpusIndex | null = null;
let indexInFlight: Promise<CorpusIndex> | null = null;

export async function loadIndex(): Promise<CorpusIndex> {
  if (indexCache) return indexCache;
  if (!indexInFlight) {
    indexInFlight = fetch('/scansion/index.json')
      .then((r) => {
        if (!r.ok) throw new Error(`scansion index: ${r.status}`);
        return r.json() as Promise<CorpusIndex>;
      })
      .then((idx) => {
        indexCache = idx;
        return idx;
      })
      .finally(() => {
        indexInFlight = null;
      });
  }
  return indexInFlight;
}

/** Load one book, memoised. Concurrent callers share a single request. */
export async function loadBook(book: number): Promise<ScansionLine[]> {
  const cached = bookCache.get(book);
  if (cached) return cached;

  const pending = inFlight.get(book);
  if (pending) return pending;

  const p = fetch(`/scansion/aen${book}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`scansion book ${book}: ${r.status}`);
      return r.json() as Promise<PackedBook>;
    })
    .then((packed) => {
      const lines = packed.l.map((l) => unpackLine(book, l));
      bookCache.set(book, lines);
      return lines;
    })
    .finally(() => {
      inFlight.delete(book);
    });

  inFlight.set(book, p);
  return p;
}

/** Books already in memory, for pickers that should not trigger a fetch. */
export function loadedBooks(): number[] {
  return [...bookCache.keys()].sort((a, b) => a - b);
}

/** A line id's book and line number, without needing the corpus loaded. */
export function parseLineId(id: string): { book: number; line: number } | null {
  const m = /^scan-aen-(\d+)-(\d+)$/.exec(id);
  if (!m) return null;
  return { book: Number(m[1]), line: Number(m[2]) };
}
